kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-mock-pvc
  labels:
    app: app-mock
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
